# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: oauth_service/authorization.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'oauth_service/authorization.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!oauth_service/authorization.proto\x12\roauth_service\x1a\x0c\x63ommon.proto\"{\n\rAuthorization\x12\x38\n\x08metadata\x18\x01 \x01(\x0b\x32&.agrirouter.common.StateChangeMetadata\x12\x30\n\x05state\x18\x02 \x01(\x0b\x32!.oauth_service.AuthorizationState\"L\n\x12\x41uthorizationState\x12\x10\n\x08tenantId\x18\x01 \x01(\t\x12\x15\n\rapplicationId\x18\x02 \x01(\t\x12\r\n\x05scope\x18\x03 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'oauth_service.authorization_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AUTHORIZATION']._serialized_start=66
  _globals['_AUTHORIZATION']._serialized_end=189
  _globals['_AUTHORIZATIONSTATE']._serialized_start=191
  _globals['_AUTHORIZATIONSTATE']._serialized_end=267
# @@protoc_insertion_point(module_scope)
