# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: feed_service/about_to_expire.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'feed_service/about_to_expire.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"feed_service/about_to_expire.proto\x12\x0c\x66\x65\x65\x64_service\x1a\x1fgoogle/protobuf/timestamp.proto\"\x99\x02\n\x1bTenantMessagesAboutToExpire\x12\x11\n\ttenant_id\x18\x01 \x01(\t\x12\x66\n\x15messages_per_endpoint\x18\x02 \x03(\x0b\x32G.feed_service.TenantMessagesAboutToExpire.EndpointMessagesAboutToExpire\x12\x32\n\x0e\x65xpirationDate\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x1aK\n\x1d\x45ndpointMessagesAboutToExpire\x12\x13\n\x0b\x65ndpoint_id\x18\x01 \x01(\t\x12\x15\n\rmessage_count\x18\x02 \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'feed_service.about_to_expire_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TENANTMESSAGESABOUTTOEXPIRE']._serialized_start=86
  _globals['_TENANTMESSAGESABOUTTOEXPIRE']._serialized_end=367
  _globals['_TENANTMESSAGESABOUTTOEXPIRE_ENDPOINTMESSAGESABOUTTOEXPIRE']._serialized_start=292
  _globals['_TENANTMESSAGESABOUTTOEXPIRE_ENDPOINTMESSAGESABOUTTOEXPIRE']._serialized_end=367
# @@protoc_insertion_point(module_scope)
