# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: feed_service/confirm_feed_messages_returned_event.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'feed_service/confirm_feed_messages_returned_event.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from feed_service import message_for_metrics_event_pb2 as feed__service_dot_message__for__metrics__event__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n7feed_service/confirm_feed_messages_returned_event.proto\x12\x0c\x66\x65\x65\x64_service\x1a,feed_service/message_for_metrics_event.proto\"\xdd\x03\n ConfirmFeedMessagesReturnedEvent\x12\x1e\n\x16\x61pplication_message_id\x18\x01 \x01(\t\x12\x12\n\nmessage_id\x18\x02 \x01(\t\x12\x13\n\x0b\x65ndpoint_id\x18\x03 \x01(\t\x12L\n\x06status\x18\x04 \x01(\x0e\x32<.feed_service.ConfirmFeedMessagesReturnedEvent.ConfirmStatus\x12%\n\x1d\x63onfirmedAndDeletedMessageIds\x18\x05 \x03(\t\x12\x1a\n\x12notFoundMessageIds\x18\x06 \x03(\t\x12\x17\n\x0fvcu_endpoint_id\x18\x07 \x01(\t\x12@\n\x12\x63onfirmed_messages\x18\x08 \x03(\x0b\x32$.feed_service.MessageForMetricsEvent\"\x83\x01\n\rConfirmStatus\x12\x1a\n\x16\x43ONFIRM_STATUS_UNKNOWN\x10\x00\x12\x07\n\x03\x41\x43K\x10\x01\x12\x0b\n\x07\x46\x41ILURE\x10\x02\x12\x1f\n\x1b\x46\x41ILURE_INFORMATION_MISSING\x10\x03\x12\x1f\n\x1b\x46\x41ILURE_QUERYDATA_MALFORMED\x10\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'feed_service.confirm_feed_messages_returned_event_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CONFIRMFEEDMESSAGESRETURNEDEVENT']._serialized_start=120
  _globals['_CONFIRMFEEDMESSAGESRETURNEDEVENT']._serialized_end=597
  _globals['_CONFIRMFEEDMESSAGESRETURNEDEVENT_CONFIRMSTATUS']._serialized_start=466
  _globals['_CONFIRMFEEDMESSAGESRETURNEDEVENT_CONFIRMSTATUS']._serialized_end=597
# @@protoc_insertion_point(module_scope)
