# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: feed_service/message_for_metrics_event.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'feed_service/message_for_metrics_event.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n,feed_service/message_for_metrics_event.proto\x12\x0c\x66\x65\x65\x64_service\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x0c\x63ommon.proto\"\xfe\x02\n\x16MessageForMetricsEvent\x12\x1e\n\x16\x61pplication_message_id\x18\x01 \x01(\t\x12\x12\n\nmessage_id\x18\x02 \x01(\t\x12\x1d\n\x15recipient_endpoint_id\x18\x03 \x01(\t\x12\x1e\n\x16technical_message_type\x18\x04 \x01(\t\x12\x14\n\x0cpayload_size\x18\x05 \x01(\x03\x12\x1e\n\x16\x61pplication_seq_number\x18\x06 \x01(\x03\x12\x1b\n\x13team_set_context_id\x18\x07 \x01(\t\x12:\n\x0f\x63hunk_component\x18\x08 \x01(\x0b\x32!.agrirouter.common.ChunkComponent\x12.\n\ncreated_at\x18\t \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x32\n\x0esent_timestamp\x18\n \x01(\x0b\x32\x1a.google.protobuf.Timestampb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'feed_service.message_for_metrics_event_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MESSAGEFORMETRICSEVENT']._serialized_start=110
  _globals['_MESSAGEFORMETRICSEVENT']._serialized_end=492
# @@protoc_insertion_point(module_scope)
