# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: feed_service/query_feed_messages_returned_event.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'feed_service/query_feed_messages_returned_event.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from feed_service import query_feed_message_headers_returned_event_pb2 as feed__service_dot_query__feed__message__headers__returned__event__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n5feed_service/query_feed_messages_returned_event.proto\x12\x0c\x66\x65\x65\x64_service\x1a\x1fgoogle/protobuf/timestamp.proto\x1a<feed_service/query_feed_message_headers_returned_event.proto\"\xd7\x07\n\x14MessageQueryResponse\x12\x31\n\rquery_metrics\x18\x01 \x01(\x0b\x32\x1a.feed_service.QueryMetrics\x12 \n\x04page\x18\x02 \x01(\x0b\x32\x12.feed_service.Page\x12@\n\x08messages\x18\x03 \x03(\x0b\x32..feed_service.MessageQueryResponse.FeedMessage\x12\x13\n\x0b\x65ndpoint_id\x18\x04 \x01(\t\x12\x12\n\nmessage_id\x18\x05 \x01(\t\x12\x1e\n\x16\x61pplication_message_id\x18\x06 \x01(\t\x12\x17\n\x0fvcu_endpoint_id\x18\x07 \x01(\t\x12\x45\n\x06status\x18\x08 \x01(\x0e\x32\x35.feed_service.MessageQueryResponse.MessageQueryStatus\x12\x14\n\x0c\x66\x61ilure_code\x18\t \x01(\t\x1a\xf3\x02\n\x06Header\x12\x13\n\x0breceiver_id\x18\x01 \x01(\t\x12\x1e\n\x16technical_message_type\x18\x02 \x01(\t\x12\x1b\n\x13team_set_context_id\x18\x03 \x01(\t\x12\x33\n\rchunk_context\x18\x04 \x01(\x0b\x32\x1c.feed_service.ChunkComponent\x12\x14\n\x0cpayload_size\x18\x05 \x01(\x03\x12\x32\n\x0esent_timestamp\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x17\n\x0fsequence_number\x18\x07 \x01(\x03\x12\x11\n\tsender_id\x18\x08 \x01(\t\x12.\n\ncreated_at\x18\t \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x12\n\nmessage_id\x18\n \x01(\t\x12(\n\x08metadata\x18\x0b \x01(\x0b\x32\x16.feed_service.Metadata\x1a\x62\n\x0b\x46\x65\x65\x64Message\x12\x39\n\x06header\x18\x01 \x01(\x0b\x32).feed_service.MessageQueryResponse.Header\x12\x18\n\x10payload_file_key\x18\x02 \x01(\t\"\x8e\x01\n\x12MessageQueryStatus\x12 \n\x1cMESSAGE_QUERY_STATUS_UNKNOWN\x10\x00\x12\x07\n\x03\x41\x43K\x10\x01\x12\x0b\n\x07\x46\x41ILURE\x10\x02\x12\x1f\n\x1b\x46\x41ILURE_INFORMATION_MISSING\x10\x03\x12\x1f\n\x1b\x46\x41ILURE_QUERYDATA_MALFORMED\x10\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'feed_service.query_feed_messages_returned_event_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MESSAGEQUERYRESPONSE']._serialized_start=167
  _globals['_MESSAGEQUERYRESPONSE']._serialized_end=1150
  _globals['_MESSAGEQUERYRESPONSE_HEADER']._serialized_start=534
  _globals['_MESSAGEQUERYRESPONSE_HEADER']._serialized_end=905
  _globals['_MESSAGEQUERYRESPONSE_FEEDMESSAGE']._serialized_start=907
  _globals['_MESSAGEQUERYRESPONSE_FEEDMESSAGE']._serialized_end=1005
  _globals['_MESSAGEQUERYRESPONSE_MESSAGEQUERYSTATUS']._serialized_start=1008
  _globals['_MESSAGEQUERYRESPONSE_MESSAGEQUERYSTATUS']._serialized_end=1150
# @@protoc_insertion_point(module_scope)
