package topics

const (
	ApplicationStateChangeTopic     = "application.state"
	SoftwareVersionStateChangeTopic = "software_version.state"
	EndpointTopic                   = "endpoint.state"
	MessageTypeEntityTopic          = "message_type.state"
	TenantEntityTopic               = "tenant.state"
	CapabilityTopic                 = "capability.state"
	RouteTopic                      = "route.state"
	SubscriptionTopic               = "subscription.state"
	RouterDeviceTopic               = "router_device.state"
	TesterStateTopic                = "tenant_tester.state"
	FarmerAccountCreatedTopic       = "farmer_account_created.event"
	DevAccountCreatedTopic          = "dev_account_created.event"
	AdminAccountCreatedTopic        = "admin_account_created.event"
	AccountDeletedTopic             = "account_deleted.event"
	DevRequestApprovedTopic         = "dev_approved.event"
	DevRequestRejectedTopic         = "dev_rejected.event"
	EmailChangedTopic               = "email_changed.event"
	EndpointIdleTopic               = "endpoint_idle.event"
	EndpointOffboardedTopic         = "endpoint_offboarded.event"
	EndpointRevokedTopic            = "endpoint_revoked.event"
	MessagesExpiredTopic            = "messages_expired.event"
	MessagesToBeExpiredTopic        = "messages_to_be_expired.event"
	PasswordChangedTopic            = "password_changed.event"
	CapabilitiesVersionUpdateEvent  = "capabilities_version_set.event"
	RoutedMessageEvent              = "routed_message.event"
	AuthorizationStateChangeTopic   = "authorization.state"

	// commands
	SetEndpointCapabilitiesTopic         = "set_endpoint_capabilities.event"
	SetEndpointCapabilitiesReturnedTopic = "set_endpoint_capabilities_returned.event"
	SetEndpointSubscriptionTopic         = "set_endpoint_subscription.event"
	SetEndpointSubscriptionReturnedTopic = "set_endpoint_subscription_returned.event"
	QueryFeedMessageHeadersTopic         = "query_feed_message_headers.event"
	QueryFeedMessageHeadersReturnedTopic = "query_feed_message_headers_returned.event"
	QueryFeedMessagesTopic               = "query_feed_messages.event"
	QueryFeedMessagesReturnedTopic       = "query_feed_messages_returned.event"
	ConfirmFeedMessagesTopic             = "confirm_feed_messages.event"
	ConfirmFeedMessagesReturnedTopic     = "confirm_feed_messages_returned.event"
	DeleteFeedMessagesTopic              = "delete_feed_messages.event"
	DeleteFeedMessagesReturnedTopic      = "delete_feed_messages_returned.event"
	ListFilteredEndpointsTopic           = "list_filtered_endpoints.event"
	ListFilteredEndpointsReturnedTopic   = "list_filtered_endpoints_returned.event"
	ListUnfilteredEndpointsTopic         = "list_unfiltered_endpoints.event"
	ListUnfilteredEndpointsReturnedTopic = "list_unfiltered_endpoints_returned.event"
	VcuOnboardEndpointsTopic             = "vcu_onboard_endpoints.event"
	VcuOnboardEndpointsReturnedTopic     = "vcu_onboard_endpoints_returned.event"
	VcuOffboardEndpointsTopic            = "vcu_offboard_endpoints.event"
	VcuOffboardEndpointsReturnedTopic    = "vcu_offboard_endpoints_returned.event"

	// metrics
	RoutedMessageDeliveredAnalyticsTopic               = "routed_message_delivered.event"
	RoutedMessageDeletedAfterOffboardingAnalyticsTopic = "routed_message_deleted_offboarded.event"
	RoutedMessageExpiredAnalyticsTopic                 = "routed_message_expired.event"

	MessageOrCommandSentAnalyticsTopic    = "message_command_sent.event"
	MessagePayloadReceivedAnalyticsTopic  = "message_payload_received.event"
	MessageOrCommandAckAnalyticsTopic     = "message_command_ack.event"
	MessageOrCommandFailureAnalyticsTopic = "message_command_failure.event"
)
