# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: application_service/application.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'application_service/application.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%application_service/application.proto\x12\x13\x61pplication_service\x1a\x0c\x63ommon.proto\"}\n\x0b\x41pplication\x12\x38\n\x08metadata\x18\x01 \x01(\x0b\x32&.agrirouter.common.StateChangeMetadata\x12\x34\n\x05state\x18\x02 \x01(\x0b\x32%.application_service.ApplicationState\"\x8c\x03\n\x10\x41pplicationState\x12\x10\n\x08tenantId\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x0c\n\x04type\x18\x04 \x01(\t\x12\x0f\n\x07logoUrl\x18\x05 \x01(\t\x12\r\n\x05\x62rand\x18\x06 \x01(\t\x12\x12\n\nsupportUrl\x18\x07 \x01(\t\x12\x0f\n\x07\x64\x65\x65pUrl\x18\x08 \x01(\t\x12\x13\n\x0bredirectUrl\x18\t \x03(\t\x12\x11\n\tpublicKey\x18\n \x01(\t\x12\x12\n\nversionTag\x18\x0b \x01(\t\x12N\n\x0f\x61pplicationType\x18\x0c \x01(\x0e\x32\x35.application_service.ApplicationState.ApplicationType\"d\n\x0f\x41pplicationType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x16\n\x12\x43OMMUNICATION_UNIT\x10\x01\x12\x14\n\x10\x46\x41RMING_SOFTWARE\x10\x02\x12\x16\n\x12TELEMETRY_PLATFORM\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'application_service.application_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_APPLICATION']._serialized_start=76
  _globals['_APPLICATION']._serialized_end=201
  _globals['_APPLICATIONSTATE']._serialized_start=204
  _globals['_APPLICATIONSTATE']._serialized_end=600
  _globals['_APPLICATIONSTATE_APPLICATIONTYPE']._serialized_start=500
  _globals['_APPLICATIONSTATE_APPLICATIONTYPE']._serialized_end=600
# @@protoc_insertion_point(module_scope)
