# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: route_service/route.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'route_service/route.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19route_service/route.proto\x12\rroute_service\x1a\x0c\x63ommon.proto\"k\n\x05Route\x12\x38\n\x08metadata\x18\x01 \x01(\x0b\x32&.agrirouter.common.StateChangeMetadata\x12(\n\x05state\x18\x02 \x01(\x0b\x32\x19.route_service.RouteState\"R\n\nCapability\x12\x1e\n\x16technical_message_type\x18\x01 \x01(\t\x12\x10\n\x08is_valid\x18\x02 \x01(\x08\x12\x12\n\nis_default\x18\x03 \x01(\x08\"3\n\x14RouteInformationType\x12\x1b\n\x13information_type_id\x18\x01 \x01(\t\"\xb3\x01\n\nRouteState\x12\n\n\x02ID\x18\x01 \x01(\t\x12\x10\n\x08SourceID\x18\x02 \x01(\t\x12\x13\n\x0bRecipientID\x18\x03 \x01(\t\x12\x10\n\x08TenantID\x18\x04 \x01(\t\x12\x14\n\x0c\x41ppVersionID\x18\x05 \x01(\t\x12\x44\n\x17route_information_types\x18\x07 \x03(\x0b\x32#.route_service.RouteInformationTypeJ\x04\x08\x06\x10\x07\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'route_service.route_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ROUTE']._serialized_start=58
  _globals['_ROUTE']._serialized_end=165
  _globals['_CAPABILITY']._serialized_start=167
  _globals['_CAPABILITY']._serialized_end=249
  _globals['_ROUTEINFORMATIONTYPE']._serialized_start=251
  _globals['_ROUTEINFORMATIONTYPE']._serialized_end=302
  _globals['_ROUTESTATE']._serialized_start=305
  _globals['_ROUTESTATE']._serialized_end=484
# @@protoc_insertion_point(module_scope)
