# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: endpoint_service/endpoint.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'endpoint_service/endpoint.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1f\x65ndpoint_service/endpoint.proto\x12\x10\x65ndpoint_service\x1a\x0c\x63ommon.proto\"t\n\x08\x45ndpoint\x12\x38\n\x08metadata\x18\x01 \x01(\x0b\x32&.agrirouter.common.StateChangeMetadata\x12.\n\x05state\x18\x02 \x01(\x0b\x32\x1f.endpoint_service.EndpointState\"\x91\x04\n\rEndpointState\x12\n\n\x02id\x18\x01 \x01(\t\x12\x10\n\x08tenantId\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x04 \x01(\t\x12\x34\n\x0c\x65ndpointType\x18\x05 \x01(\x0e\x32\x1e.endpoint_service.EndpointType\x12\x16\n\x0eisDefaultGroup\x18\x06 \x01(\x08\x12\x14\n\x0c\x61ppVersionId\x18\x07 \x01(\t\x12\x15\n\risDeactivated\x18\x08 \x01(\x08\x12\x12\n\nexternalId\x18\t \x01(\t\x12\x16\n\x0emachineClassId\x18\n \x01(\t\x12\x12\n\ndesignator\x18\x0b \x01(\t\x12\x17\n\x0bmachineDDIs\x18\x0c \x03(\x05\x42\x02\x10\x01\x12\x1a\n\x12originalEndpointId\x18\r \x01(\t\x12\x16\n\x0epairedTenantId\x18\x0e \x01(\t\x12\x11\n\tpairingId\x18\x0f \x01(\t\x12\x14\n\x0cisSubscribed\x18\x10 \x01(\x08\x12\x18\n\x10virtualCuOwnerId\x18\x11 \x01(\t\x12\x12\n\nversionTag\x18\x12 \x01(\t\x12.\n\tgatewayId\x18\x13 \x01(\x0e\x32\x1b.endpoint_service.GatewayId\x12\x15\n\rapplicationId\x18\x14 \x01(\t\x12\x19\n\x11\x64\x65viceAlternateId\x18\x15 \x01(\t*\x94\x01\n\x0c\x45ndpointType\x12\x19\n\x15\x45NDPOINT_TYPE_UNKNOWN\x10\x00\x12\x19\n\x15\x41GRICULTURAL_SOFTWARE\x10\x01\x12\x16\n\x12\x43OMMUNICATION_UNIT\x10\x02\x12\x1e\n\x1aVIRTUAL_COMMUNICATION_UNIT\x10\x03\x12\x16\n\x12TELEMETRY_PLATFORM\x10\x04*I\n\tGatewayId\x12\x16\n\x12UNKNOWN_GATEWAY_ID\x10\x00\x12\x08\n\x04NONE\x10\x01\x12\x08\n\x04MQTT\x10\x02\x12\x08\n\x04HTTP\x10\x03\x12\x06\n\x02G4\x10\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'endpoint_service.endpoint_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ENDPOINTSTATE'].fields_by_name['machineDDIs']._loaded_options = None
  _globals['_ENDPOINTSTATE'].fields_by_name['machineDDIs']._serialized_options = b'\020\001'
  _globals['_ENDPOINTTYPE']._serialized_start=718
  _globals['_ENDPOINTTYPE']._serialized_end=866
  _globals['_GATEWAYID']._serialized_start=868
  _globals['_GATEWAYID']._serialized_end=941
  _globals['_ENDPOINT']._serialized_start=67
  _globals['_ENDPOINT']._serialized_end=183
  _globals['_ENDPOINTSTATE']._serialized_start=186
  _globals['_ENDPOINTSTATE']._serialized_end=715
# @@protoc_insertion_point(module_scope)
