# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: endpoint_service/list_unfiltered_endpoints_returned_event.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'endpoint_service/list_unfiltered_endpoints_returned_event.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n?endpoint_service/list_unfiltered_endpoints_returned_event.proto\x12\x10\x65ndpoint_service\"\xdd\x05\n\x15ListEndpointsResponse\x12>\n\x06status\x18\x01 \x01(\x0e\x32..endpoint_service.ListEndpointsResponse.Status\x12\x43\n\tendpoints\x18\x02 \x03(\x0b\x32\x30.endpoint_service.ListEndpointsResponse.Endpoint\x12\x12\n\nmessage_id\x18\x03 \x01(\t\x12\x1e\n\x16\x61pplication_message_id\x18\x04 \x01(\t\x12\x13\n\x0b\x65ndpoint_id\x18\x05 \x01(\t\x12\x17\n\x0fvcu_endpoint_id\x18\x06 \x01(\t\x1as\n\x0bMessageType\x12\x1e\n\x16technical_message_type\x18\x01 \x01(\t\x12\x44\n\tdirection\x18\x02 \x01(\x0e\x32\x31.endpoint_service.ListEndpointsResponse.Direction\x1a\xbe\x01\n\x08\x45ndpoint\x12\x13\n\x0b\x65ndpoint_id\x18\x01 \x01(\t\x12\x15\n\rendpoint_name\x18\x02 \x01(\t\x12\x15\n\rendpoint_type\x18\x03 \x01(\t\x12\x0e\n\x06status\x18\x04 \x01(\t\x12J\n\rmessage_types\x18\x05 \x03(\x0b\x32\x33.endpoint_service.ListEndpointsResponse.MessageType\x12\x13\n\x0b\x65xternal_id\x18\x06 \x01(\t\"K\n\tDirection\x12\x15\n\x11UNKNOWN_DIRECTION\x10\x00\x12\x08\n\x04SEND\x10\x01\x12\x0b\n\x07RECEIVE\x10\x02\x12\x10\n\x0cSEND_RECEIVE\x10\x03\"Z\n\x06Status\x12\x12\n\x0eUNKNOWN_STATUS\x10\x00\x12\x07\n\x03\x41\x43K\x10\x01\x12\x14\n\x10\x41\x43K_WITH_FAILURE\x10\x02\x12\x1d\n\x19\x41\x43K_WITH_VALIDATION_ERROR\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'endpoint_service.list_unfiltered_endpoints_returned_event_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LISTENDPOINTSRESPONSE']._serialized_start=86
  _globals['_LISTENDPOINTSRESPONSE']._serialized_end=819
  _globals['_LISTENDPOINTSRESPONSE_MESSAGETYPE']._serialized_start=342
  _globals['_LISTENDPOINTSRESPONSE_MESSAGETYPE']._serialized_end=457
  _globals['_LISTENDPOINTSRESPONSE_ENDPOINT']._serialized_start=460
  _globals['_LISTENDPOINTSRESPONSE_ENDPOINT']._serialized_end=650
  _globals['_LISTENDPOINTSRESPONSE_DIRECTION']._serialized_start=652
  _globals['_LISTENDPOINTSRESPONSE_DIRECTION']._serialized_end=727
  _globals['_LISTENDPOINTSRESPONSE_STATUS']._serialized_start=729
  _globals['_LISTENDPOINTSRESPONSE_STATUS']._serialized_end=819
# @@protoc_insertion_point(module_scope)
