# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: endpoint_service/router_device.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'endpoint_service/router_device.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$endpoint_service/router_device.proto\x12\x10\x65ndpoint_service\x1a\x0c\x63ommon.proto\"|\n\x0cRouterDevice\x12\x38\n\x08metadata\x18\x01 \x01(\x0b\x32&.agrirouter.common.StateChangeMetadata\x12\x32\n\x05state\x18\x02 \x01(\x0b\x32#.endpoint_service.RouterDeviceState\"^\n\x11RouterDeviceState\x12\n\n\x02id\x18\x01 \x01(\t\x12\x10\n\x08tenantId\x18\x02 \x01(\t\x12\x10\n\x08\x63lientId\x18\x03 \x01(\t\x12\x19\n\x11\x64\x65viceAlternateId\x18\x04 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'endpoint_service.router_device_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ROUTERDEVICE']._serialized_start=72
  _globals['_ROUTERDEVICE']._serialized_end=196
  _globals['_ROUTERDEVICESTATE']._serialized_start=198
  _globals['_ROUTERDEVICESTATE']._serialized_end=292
# @@protoc_insertion_point(module_scope)
