# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: endpoint_service/vcu_onboard_endpoints_returned_event.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'endpoint_service/vcu_onboard_endpoints_returned_event.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from endpoint_service import vcu_message_pb2 as endpoint__service_dot_vcu__message__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n;endpoint_service/vcu_onboard_endpoints_returned_event.proto\x12\x10\x65ndpoint_service\x1a\"endpoint_service/vcu_message.proto\"\xbe\x04\n VcuOnboardEndpointsReturnedEvent\x12k\n\x13onboarded_endpoints\x18\x01 \x03(\x0b\x32N.endpoint_service.VcuOnboardEndpointsReturnedEvent.EndpointRegistrationDetails\x12M\n\x08\x66\x61ilures\x18\x02 \x03(\x0b\x32;.endpoint_service.VcuOnboardEndpointsReturnedEvent.Failures\x12\x36\n\x06status\x18\x03 \x01(\x0e\x32&.endpoint_service.OnboardRequestStatus\x12\x1e\n\x16\x61pplication_message_id\x18\x04 \x01(\t\x12\x12\n\nmessage_id\x18\x05 \x01(\t\x12\x13\n\x0b\x65ndpoint_id\x18\x06 \x01(\t\x1a\x99\x01\n\x1b\x45ndpointRegistrationDetails\x12\n\n\x02id\x18\x01 \x01(\t\x12\x1b\n\x13\x64\x65vice_alternate_id\x18\x02 \x01(\t\x12\x1b\n\x13sensor_alternate_id\x18\x03 \x01(\t\x12\x1f\n\x17\x63\x61pability_alternate_id\x18\x04 \x01(\t\x12\x13\n\x0b\x65ndpoint_id\x18\x05 \x01(\t\x1a\x41\n\x08\x46\x61ilures\x12\n\n\x02id\x18\x01 \x01(\t\x12)\n\x06reason\x18\x02 \x01(\x0b\x32\x19.endpoint_service.Message*\x91\x02\n\x14OnboardRequestStatus\x12 \n\x1cOnboardRequestStatus_UNKNOWN\x10\x00\x12 \n\x1cOnboardRequestStatus_SUCCESS\x10\x01\x12(\n$OnboardRequestStatus_PARTIAL_SUCCESS\x10\x02\x12 \n\x1cOnboardRequestStatus_FAILURE\x10\x03\x12\x37\n3OnboardRequestStatus_FAILURE_NOT_TELEMETRY_PLATFORM\x10\x04\x12\x30\n,OnboardRequestStatus_NO_ENDPOINTS_TO_ONBOARD\x10\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'endpoint_service.vcu_onboard_endpoints_returned_event_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ONBOARDREQUESTSTATUS']._serialized_start=695
  _globals['_ONBOARDREQUESTSTATUS']._serialized_end=968
  _globals['_VCUONBOARDENDPOINTSRETURNEDEVENT']._serialized_start=118
  _globals['_VCUONBOARDENDPOINTSRETURNEDEVENT']._serialized_end=692
  _globals['_VCUONBOARDENDPOINTSRETURNEDEVENT_ENDPOINTREGISTRATIONDETAILS']._serialized_start=472
  _globals['_VCUONBOARDENDPOINTSRETURNEDEVENT_ENDPOINTREGISTRATIONDETAILS']._serialized_end=625
  _globals['_VCUONBOARDENDPOINTSRETURNEDEVENT_FAILURES']._serialized_start=627
  _globals['_VCUONBOARDENDPOINTSRETURNEDEVENT_FAILURES']._serialized_end=692
# @@protoc_insertion_point(module_scope)
