# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: endpoint_service/vcu_offboard_endpoints_returned_event.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'endpoint_service/vcu_offboard_endpoints_returned_event.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from endpoint_service import vcu_message_pb2 as endpoint__service_dot_vcu__message__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n<endpoint_service/vcu_offboard_endpoints_returned_event.proto\x12\x10\x65ndpoint_service\x1a\"endpoint_service/vcu_message.proto\"\xd6\x02\n!VcuOffboardEndpointsReturnedEvent\x12\x1c\n\x14offboarded_endpoints\x18\x01 \x03(\t\x12N\n\x08\x66\x61ilures\x18\x02 \x03(\x0b\x32<.endpoint_service.VcuOffboardEndpointsReturnedEvent.Failures\x12\x37\n\x06status\x18\x03 \x01(\x0e\x32\'.endpoint_service.OffboardRequestStatus\x12\x1e\n\x16\x61pplication_message_id\x18\x04 \x01(\t\x12\x12\n\nmessage_id\x18\x05 \x01(\t\x12\x13\n\x0b\x65ndpoint_id\x18\x06 \x01(\t\x1a\x41\n\x08\x46\x61ilures\x12\n\n\x02id\x18\x01 \x01(\t\x12)\n\x06reason\x18\x02 \x01(\x0b\x32\x19.endpoint_service.Message*\xab\x01\n\x15OffboardRequestStatus\x12!\n\x1dOffboardRequestStatus_UNKNOWN\x10\x00\x12!\n\x1dOffboardRequestStatus_SUCCESS\x10\x01\x12)\n%OffboardRequestStatus_PARTIAL_SUCCESS\x10\x02\x12!\n\x1dOffboardRequestStatus_FAILURE\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'endpoint_service.vcu_offboard_endpoints_returned_event_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_OFFBOARDREQUESTSTATUS']._serialized_start=464
  _globals['_OFFBOARDREQUESTSTATUS']._serialized_end=635
  _globals['_VCUOFFBOARDENDPOINTSRETURNEDEVENT']._serialized_start=119
  _globals['_VCUOFFBOARDENDPOINTSRETURNEDEVENT']._serialized_end=461
  _globals['_VCUOFFBOARDENDPOINTSRETURNEDEVENT_FAILURES']._serialized_start=396
  _globals['_VCUOFFBOARDENDPOINTSRETURNEDEVENT_FAILURES']._serialized_end=461
# @@protoc_insertion_point(module_scope)
