# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: message_type_service/technical_message_type.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'message_type_service/technical_message_type.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n1message_type_service/technical_message_type.proto\x12\x14message_type_service\x1a\x0c\x63ommon.proto\"~\n\x0bMessageType\x12\x38\n\x08metadata\x18\x01 \x01(\x0b\x32&.agrirouter.common.StateChangeMetadata\x12\x35\n\x05state\x18\x02 \x01(\x0b\x32&.message_type_service.MessageTypeState\"S\n\x10MessageTypeState\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x1c\n\x14information_type_ids\x18\x03 \x03(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'message_type_service.technical_message_type_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MESSAGETYPE']._serialized_start=89
  _globals['_MESSAGETYPE']._serialized_end=215
  _globals['_MESSAGETYPESTATE']._serialized_start=217
  _globals['_MESSAGETYPESTATE']._serialized_end=300
# @@protoc_insertion_point(module_scope)
