# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: account_service/tenant.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'account_service/tenant.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1c\x61\x63\x63ount_service/tenant.proto\x12\x0f\x61\x63\x63ount_service\x1a\x0c\x63ommon.proto\"o\n\x06Tenant\x12\x38\n\x08metadata\x18\x01 \x01(\x0b\x32&.agrirouter.common.StateChangeMetadata\x12+\n\x05state\x18\x02 \x01(\x0b\x32\x1c.account_service.TenantState\"\x9a\x01\n\x0bTenantState\x12\n\n\x02id\x18\x01 \x01(\t\x12\x13\n\x0b\x63ompanyName\x18\x02 \x01(\t\x12\x1f\n\x12\x63ompanyDescription\x18\x03 \x01(\tH\x00\x88\x01\x01\x12\x1d\n\x10manufacturerCode\x18\x04 \x01(\tH\x01\x88\x01\x01\x42\x15\n\x13_companyDescriptionB\x13\n\x11_manufacturerCode\"\x1a\n\x0cTenantDelete\x12\n\n\x02id\x18\x01 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'account_service.tenant_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TENANT']._serialized_start=63
  _globals['_TENANT']._serialized_end=174
  _globals['_TENANTSTATE']._serialized_start=177
  _globals['_TENANTSTATE']._serialized_end=331
  _globals['_TENANTDELETE']._serialized_start=333
  _globals['_TENANTDELETE']._serialized_end=359
# @@protoc_insertion_point(module_scope)
