# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: account_service/tenant_tester.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'account_service/tenant_tester.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#account_service/tenant_tester.proto\x12\x0f\x61\x63\x63ount_service\x1a\x0c\x63ommon.proto\"u\n\x0cTenantTester\x12\x38\n\x08metadata\x18\x01 \x01(\x0b\x32&.agrirouter.common.StateChangeMetadata\x12+\n\x05state\x18\x02 \x01(\x0b\x32\x1c.account_service.TesterState\"\xdb\x01\n\x0bTesterState\x12\n\n\x02id\x18\x01 \x01(\t\x12\x17\n\x0fowner_tenant_id\x18\x02 \x01(\t\x12\x18\n\x10tester_tenant_id\x18\x03 \x01(\t\x12\x39\n\x06status\x18\x04 \x01(\x0e\x32).account_service.TesterState.TesterStatus\"R\n\x0cTesterStatus\x12\x19\n\x15TESTER_STATUS_UNKNOWN\x10\x00\x12\x0b\n\x07\x43REATED\x10\x01\x12\x0c\n\x08\x41\x43\x43\x45PTED\x10\x02\x12\x0c\n\x08REJECTED\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'account_service.tenant_tester_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TENANTTESTER']._serialized_start=70
  _globals['_TENANTTESTER']._serialized_end=187
  _globals['_TESTERSTATE']._serialized_start=190
  _globals['_TESTERSTATE']._serialized_end=409
  _globals['_TESTERSTATE_TESTERSTATUS']._serialized_start=327
  _globals['_TESTERSTATE_TESTERSTATUS']._serialized_end=409
# @@protoc_insertion_point(module_scope)
