# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: account_service/user.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'account_service/user.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x61\x63\x63ount_service/user.proto\x12\x0f\x61\x63\x63ount_service\x1a\x0c\x63ommon.proto\"[\n\x04User\x12\x38\n\x08metadata\x18\x01 \x01(\x0b\x32&.agrirouter.common.StateChangeMetadata\x12\n\n\x02id\x18\x02 \x01(\t\x12\r\n\x05state\x18\x03 \x01(\t\"\x18\n\nUserDelete\x12\n\n\x02id\x18\x01 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'account_service.user_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USER']._serialized_start=61
  _globals['_USER']._serialized_end=152
  _globals['_USERDELETE']._serialized_start=154
  _globals['_USERDELETE']._serialized_end=178
# @@protoc_insertion_point(module_scope)
