# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gateway_service/query_feed_message_headers_event.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'gateway_service/query_feed_message_headers_event.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from gateway_service import validity_period_pb2 as gateway__service_dot_validity__period__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n6gateway_service/query_feed_message_headers_event.proto\x12\x0fgateway_service\x1a\x1fgoogle/protobuf/timestamp.proto\x1a%gateway_service/validity_period.proto\"\x8f\x02\n\x1cQueryFeedMessageHeadersEvent\x12\x13\n\x0bmessage_ids\x18\x01 \x03(\t\x12\x0f\n\x07senders\x18\x02 \x03(\t\x12\x38\n\x0fvalidity_period\x18\x03 \x01(\x0b\x32\x1f.gateway_service.ValidityPeriod\x12-\n\ttimestamp\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x1e\n\x16\x61pplication_message_id\x18\x05 \x01(\t\x12\x13\n\x0b\x65ndpoint_id\x18\x06 \x01(\t\x12\x12\n\nmessage_id\x18\x07 \x01(\t\x12\x17\n\x0fvcu_endpoint_id\x18\x08 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gateway_service.query_feed_message_headers_event_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_QUERYFEEDMESSAGEHEADERSEVENT']._serialized_start=148
  _globals['_QUERYFEEDMESSAGEHEADERSEVENT']._serialized_end=419
# @@protoc_insertion_point(module_scope)
