# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gateway_service/routed_message_event.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'gateway_service/routed_message_event.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n*gateway_service/routed_message_event.proto\x12\x0fgateway_service\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x0c\x63ommon.proto\"\xd2\x03\n\x12RoutedMessageEvent\x12\x12\n\nmessage_id\x18\x01 \x01(\t\x12\x11\n\tsource_id\x18\x02 \x01(\t\x12\x14\n\x0cmessage_type\x18\x03 \x01(\t\x12\x1e\n\x16\x61pplication_seq_number\x18\x04 \x01(\x03\x12\x15\n\rrecipient_ids\x18\x05 \x03(\t\x12\x1b\n\x13team_set_context_id\x18\x06 \x01(\t\x12-\n\ttimestamp\x18\x07 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12:\n\x0f\x63hunk_component\x18\x08 \x01(\x0b\x32!.agrirouter.common.ChunkComponent\x12-\n\x08metadata\x18\t \x01(\x0b\x32\x1b.agrirouter.common.Metadata\x12\x14\n\x0cpayload_size\x18\n \x01(\x03\x12\x18\n\x10payload_file_key\x18\x0b \x01(\t\x12.\n\ncreated_at\x18\x0c \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x1e\n\x16\x61pplication_message_id\x18\r \x01(\t\x12\x11\n\ttenant_id\x18\x0e \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gateway_service.routed_message_event_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ROUTEDMESSAGEEVENT']._serialized_start=111
  _globals['_ROUTEDMESSAGEEVENT']._serialized_end=577
# @@protoc_insertion_point(module_scope)
