# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gateway_service/set_endpoint_capabilities_event.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'gateway_service/set_endpoint_capabilities_event.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n5gateway_service/set_endpoint_capabilities_event.proto\x12\x0fgateway_service\x1a\x1fgoogle/protobuf/timestamp.proto\"\xae\x05\n\x1cSetEndpointCapabilitiesEvent\x12N\n\x0c\x63\x61pabilities\x18\x01 \x03(\x0b\x32\x38.gateway_service.SetEndpointCapabilitiesEvent.Capability\x12\x1c\n\x14\x61pp_certification_id\x18\x02 \x01(\t\x12$\n\x1c\x61pp_certification_version_id\x18\x03 \x01(\t\x12\x61\n\x19\x65nable_push_notifications\x18\x04 \x01(\x0e\x32>.gateway_service.SetEndpointCapabilitiesEvent.PushNotification\x12-\n\ttimestamp\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x1e\n\x16\x61pplication_message_id\x18\x06 \x01(\t\x12\x13\n\x0b\x65ndpoint_id\x18\x07 \x01(\t\x12\x12\n\nmessage_id\x18\x08 \x01(\t\x12\x17\n\x0fvcu_endpoint_id\x18\t \x01(\t\x1ax\n\nCapability\x12\x1e\n\x16technical_message_type\x18\x01 \x01(\t\x12J\n\tdirection\x18\x02 \x01(\x0e\x32\x37.gateway_service.SetEndpointCapabilitiesEvent.Direction\"A\n\tDirection\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x08\n\x04SEND\x10\x01\x12\x0b\n\x07RECEIVE\x10\x02\x12\x10\n\x0cSEND_RECEIVE\x10\x03\"I\n\x10PushNotification\x12\x0c\n\x08\x44ISABLED\x10\x00\x12\x0b\n\x07\x45NABLED\x10\x01\x12\x1a\n\x16\x45NABLED_HIGH_FREQUENCY\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gateway_service.set_endpoint_capabilities_event_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SETENDPOINTCAPABILITIESEVENT']._serialized_start=108
  _globals['_SETENDPOINTCAPABILITIESEVENT']._serialized_end=794
  _globals['_SETENDPOINTCAPABILITIESEVENT_CAPABILITY']._serialized_start=532
  _globals['_SETENDPOINTCAPABILITIESEVENT_CAPABILITY']._serialized_end=652
  _globals['_SETENDPOINTCAPABILITIESEVENT_DIRECTION']._serialized_start=654
  _globals['_SETENDPOINTCAPABILITIESEVENT_DIRECTION']._serialized_end=719
  _globals['_SETENDPOINTCAPABILITIESEVENT_PUSHNOTIFICATION']._serialized_start=721
  _globals['_SETENDPOINTCAPABILITIESEVENT_PUSHNOTIFICATION']._serialized_end=794
# @@protoc_insertion_point(module_scope)
