# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: capability_service/capability.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'capability_service/capability.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#capability_service/capability.proto\x12\x12\x63\x61pability_service\x1a\x0c\x63ommon.proto\"\x94\x01\n\x17\x43\x61pabilitySpecification\x12\x38\n\x08metadata\x18\x01 \x01(\x0b\x32&.agrirouter.common.StateChangeMetadata\x12?\n\x05state\x18\x02 \x01(\x0b\x32\x30.capability_service.CapabilitySpecificationState\"\xac\x01\n\nCapability\x12;\n\tdirection\x18\x01 \x01(\x0e\x32(.capability_service.Capability.Direction\x12\x1e\n\x16technical_message_type\x18\x02 \x01(\t\"A\n\tDirection\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x08\n\x04SEND\x10\x01\x12\x0b\n\x07RECEIVE\x10\x02\x12\x10\n\x0cSEND_RECEIVE\x10\x03\"\xc8\x01\n\x1c\x43\x61pabilitySpecificationState\x12\x13\n\x0b\x65ndpoint_id\x18\x01 \x01(\t\x12\x16\n\x0e\x61pp_version_id\x18\x02 \x01(\t\x12\x34\n\x0c\x63\x61pabilities\x18\x03 \x03(\x0b\x32\x1e.capability_service.Capability\x12\x45\n\x17\x45nablePushNotifications\x18\x04 \x01(\x0e\x32$.capability_service.PushNotification*\x9a\x01\n\x10PushNotification\x12\x1c\n\x18PushNotification_UNKNOWN\x10\x00\x12\x1d\n\x19PushNotification_DISABLED\x10\x01\x12\x1c\n\x18PushNotification_ENABLED\x10\x02\x12+\n\'PushNotification_ENABLED_HIGH_FREQUENCY\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'capability_service.capability_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PUSHNOTIFICATION']._serialized_start=603
  _globals['_PUSHNOTIFICATION']._serialized_end=757
  _globals['_CAPABILITYSPECIFICATION']._serialized_start=74
  _globals['_CAPABILITYSPECIFICATION']._serialized_end=222
  _globals['_CAPABILITY']._serialized_start=225
  _globals['_CAPABILITY']._serialized_end=397
  _globals['_CAPABILITY_DIRECTION']._serialized_start=332
  _globals['_CAPABILITY_DIRECTION']._serialized_end=397
  _globals['_CAPABILITYSPECIFICATIONSTATE']._serialized_start=400
  _globals['_CAPABILITYSPECIFICATIONSTATE']._serialized_end=600
# @@protoc_insertion_point(module_scope)
