# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: capability_service/set_endpoint_capabilities_returned_event.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'capability_service/set_endpoint_capabilities_returned_event.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nAcapability_service/set_endpoint_capabilities_returned_event.proto\x12\x12\x63\x61pability_service\"\x99\x03\n$SetEndpointCapabilitiesReturnedEvent\x12\x1e\n\x16\x61pplication_message_id\x18\x01 \x01(\t\x12\x12\n\nmessage_id\x18\x02 \x01(\t\x12O\n\x06status\x18\x03 \x01(\x0e\x32?.capability_service.SetEndpointCapabilitiesReturnedEvent.Status\x12\x1a\n\x12\x66\x61iledMessageTypes\x18\x04 \x03(\t\x12\x13\n\x0b\x65ndpoint_id\x18\x05 \x01(\t\x12\x17\n\x0fvcu_endpoint_id\x18\x06 \x01(\t\"\xa1\x01\n\x06Status\x12\x0b\n\x07UNKNOWN\x10\x00\x12\r\n\tNO_CHANGE\x10\x01\x12\n\n\x06\x41LL_OK\x10\x02\x12\x14\n\x10\x42\x41\x44_CAPABILITIES\x10\x03\x12\x1c\n\x18INVALID_SOFTWARE_VERSION\x10\x04\x12\x17\n\x13INVALID_APPLICATION\x10\x05\x12\x12\n\x0eINTERNAL_ERROR\x10\x06\x12\x0e\n\nBAD_TESTER\x10\x07\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'capability_service.set_endpoint_capabilities_returned_event_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SETENDPOINTCAPABILITIESRETURNEDEVENT']._serialized_start=90
  _globals['_SETENDPOINTCAPABILITIESRETURNEDEVENT']._serialized_end=499
  _globals['_SETENDPOINTCAPABILITIESRETURNEDEVENT_STATUS']._serialized_start=338
  _globals['_SETENDPOINTCAPABILITIESRETURNEDEVENT_STATUS']._serialized_end=499
# @@protoc_insertion_point(module_scope)
