# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: capability_service/subscription.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'capability_service/subscription.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%capability_service/subscription.proto\x12\x12\x63\x61pability_service\x1a\x0c\x63ommon.proto\"~\n\x0cSubscription\x12\x38\n\x08metadata\x18\x01 \x01(\x0b\x32&.agrirouter.common.StateChangeMetadata\x12\x34\n\x05state\x18\x02 \x01(\x0b\x32%.capability_service.SubscriptionState\"\x8d\x01\n\x11SubscriptionState\x12P\n\x17technical_message_types\x18\x01 \x03(\x0b\x32/.capability_service.MessageTypeSubscriptionItem\x12\x13\n\x0b\x65ndpoint_id\x18\x02 \x01(\t\x12\x11\n\ttenant_id\x18\x03 \x01(\t\"I\n\x1bMessageTypeSubscriptionItem\x12\x1e\n\x16technical_message_type\x18\x01 \x01(\tJ\x04\x08\x02\x10\x03J\x04\x08\x03\x10\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'capability_service.subscription_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SUBSCRIPTION']._serialized_start=75
  _globals['_SUBSCRIPTION']._serialized_end=201
  _globals['_SUBSCRIPTIONSTATE']._serialized_start=204
  _globals['_SUBSCRIPTIONSTATE']._serialized_end=345
  _globals['_MESSAGETYPESUBSCRIPTIONITEM']._serialized_start=347
  _globals['_MESSAGETYPESUBSCRIPTIONITEM']._serialized_end=420
# @@protoc_insertion_point(module_scope)
